# Generated by Django 2.1.7 on 2019-03-30 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('donor', 'Donor'), ('seeker', 'Seeker'), ('volunteer', 'Volunteer')], max_length=50)),
                ('image', models.ImageField(upload_to='profile_picture')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_aproved', models.BooleanField(blank=True, default=False, null=True)),
                ('update', models.CharField(help_text='Did seeker get the help?', max_length=200)),
                ('nid', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='post')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='SeekerApp.People')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeekerApp.People')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeekerApp.People'),
        ),
        migrations.AddField(
            model_name='payment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeekerApp.Post'),
        ),
    ]
