# Generated by Django 2.1.7 on 2019-03-29 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SeekerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_aproved', models.BooleanField(blank=True, default=False, null=True)),
                ('update', models.CharField(help_text='Did seeker get the help?', max_length=200)),
                ('nid', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='post')),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='post',
            name='verified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SeekerApp.People'),
        ),
    ]
