# Generated by Django 2.1.7 on 2019-04-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeekerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='verified_by',
        ),
        migrations.AlterField(
            model_name='post',
            name='update',
            field=models.CharField(default='Not get help', help_text='Did seeker get the help?', max_length=200),
        ),
    ]
